5   Q$=CHR$(34)
10  ?
20  ? "                                       "
30  ? "    APPLESOFT ROMXC/E IMAGE MAKER      "
40  ? "                                       "
50  ? "Welcome! This disk allows you to create"
60  ? "ROM images that will automatically     "
70  ? "load and run a program in basic        "
80  ? "upon booting.                          "
90  ? "                                       "
100 ? "STEPS:                                 "
110 ? "1. Load your BASIC program.            "
120 ? "2. ] BRUN MAKE ASOFT ROM               "
130 ? "3. Upload resulting ROM via the        "
140 ? "   ROMXc/e menu.  *                    "
150 ? "4. Use ";Q$;"&Sx";Q$;" in the description to     "
160 ? "   chain-load your preferred ";Q$;"main";Q$;"    "
170 ? "   ROM.  *                             "
180 ? "                                       "
190 ? " * See your ROMXc/e manual             "
200 ? "                                       "
210 ? "https://github.com/micahcowan/romx-basic"
